### ISSUE TITLE
vsftpd 无法启动

### ISSUE THREAD

**Issue by 0bo** [animefansxj/luci-app-vsftpd#1]
你好，我下载了ipk目录下的所有文件进行了安装成功后，vsftpd无法启动，/etc/init.d/vsftpd start显示：

root@OpenWrt:/usr/sbin# /etc/init.d/vsftpd start
sh: 1: unknown operand
sh: 1: unknown operand
sh: 0: unknown operand
/etc/rc.common: line 1: db_load: not found
start-stop-daemon: can't execute '/usr/sbin/vsftpd': No such file or directory

（'/usr/sbin/vsftpd'是存在的，有这个文件，权限设置也正常）

用的是703n，装15.05.1后系统只剩下200K，甚至没有办法完成overlay迁移到u盘来扩展空间，故使用了最新的DESIGNATED DRIVER (Bleeding Edge, r49390)。是与系统有关么？

谢谢！

**Comment by animefansxj** [comment]
db_load: not found  :   看下db47和libdb47是否安装
/usr/sbin/vsftpd': No such file or directory  :  提示就是找不到这个文件，如果确定存在这个文件，看看它能不能执行

#cd /usr/sbin/vsftpd
#./vsftpd --help

看看vsftpd有没有打印出什么来。

**Comment by animefansxj** [comment]
如果无法启动，也可能是系统的问题，DD相对CC有很大的改动，底层C函数库从ulibc改为muslibc了
因为我不编译测试版，所以没试过和DD的兼容性
如果可能，能否试着从源码编译一个看看是不是还有这样的问题

**Comment by 0bo** [comment]
opkg list-installed 显示有:
db47 - 4.7.25.4.NC-4.1
libdb47 - 4.7.25.4.NC-4.1
libpam - 1.1.8-4
vsftpd - 2.3.4-1

cd /usr/sbin/
./vsftpd --help 显示：
-ash: ./vsftpd: not found
还是找不到的，在cc下编译的程序不能在dd下运行么？

我试了装dd自带的vsftp，版本是3.03了，可以启动但是luci-app是没有反应的，应该是您的这几个包都是相互依赖的吧。

我想换cc 15.05.1，但是官方那个镜像装完只有230+k空间，没法儿安装必要组件来吧overlay移到u盘去。我试着删除luci和uhttp，删除后竟然发现空间更小了大概只有80k。是因为那些包是固件内编译的，所以无法删除吗？还有什么办法可以安装更为纯净的cc？而且cc装完根目录下只有512k，而dd下却有730+k，剩余空间有400K

刚玩儿openwrt，请不吝赐教。

谢谢您这么快速的答复！

**Comment by animefansxj** [comment]
你固件的根文件系统是squashfs文件系统的，这是个只读文件系统，通过叠加在上面的另一个可写分区(一般是采用JFFS文件系统或者EXT4文件系统)来实现这个文件系统的可写的。你删除了只读文件系统里面的一个文件实际是在可写分区中创建了一个标记文件，所以反而占用了空间。

4M的闪存要运行支持USB的Openwrt倒是挺难办的，200K的空间光是安装kmod-fs-ext4可能都不够。

**Comment by animefansxj** [comment]
你好，刚才我自己刷了DD后安装了一下，已经确定是因为openwrt DD 使用musl代替uclibc导致找不到libc.so.0和libdl.so.0，无法调用__ctype_tolower、__uClibc_main、fcntl64、__ctype_b等功能导致的。

> ldd /usr/sbin/vsftpd
>         /lib/ld-uClibc.so.0 (0x55746000)
> Error loading shared library libcrypt.so.0: No such file or directory (needed by /usr/sbin/vsftpd)
>         libpam.so.0 => /lib/libpam.so.0 (0x773e4000)
>         libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x773c0000)
>         libc.so.0 => /lib/ld-uClibc.so.0 (0x55746000)
>         libdl.so.0 => /lib/ld-uClibc.so.0 (0x55746000)
> Error relocating /lib/libpam.so.0: __ctype_tolower: symbol not found
> Error relocating /usr/sbin/vsftpd: __uClibc_main: symbol not found
> Error relocating /usr/sbin/vsftpd: fcntl64: symbol not found
> Error relocating /usr/sbin/vsftpd: __ctype_b: symbol not found

解决方法只有安装CC固件或者使用DD源代码重新编译。因此这个issue就关掉了。

**Comment by 0bo** [comment]
谢谢您！在研究编译cc固件，可惜几个vps都是32位的14.04。。。改天有时间重装了试试哈。

也希望有天能见到dd重新编译版的。

祝好！
